solver:  
  gradient_accumulation_steps: 1
  mixed_precision: 'fp16'
  enable_xformers_memory_efficient_attention: false
  gradient_checkpointing: false 
  max_train_steps: 4000000
  max_grad_norm: 1.0
  # lr
  learning_rate: 1e-5
  scale_lr: false 
  lr_warmup_steps: 1
  lr_scheduler: 'constant'

  # optimizer
  use_8bit_adam: false 
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay:  1.0e-2
  adam_epsilon: 1.0e-8

val:
  validation_steps: 1000
  validation_steps_tuple: []

train_bs: 24

weight_dtype: 'fp32'  # [fp16, fp32]
uncond_ratio: 0.

skip_timestep: 50
seed: 12580
resume_from_checkpoint: 'latest'
exp_name: 'scaled_vprediction_simplified_stage1'
output_dir: './exp_output'

prediction_type: "epsilon"